/* This file was generated by SableCC (http://www.sablecc.org/). */

package coolc.compiler.autogen.node;

/* This file was generated by SableCC (http://www.sablecc.org/). */

import java.util.*;

import coolc.compiler.visitors.WithPrintableType;

@SuppressWarnings("nls")
public abstract class Node implements Switchable, Cloneable, WithPrintableType
{
    private Node parent;
    private String type;
    private String inClass;
    private int number;
    
    
    public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getInClass() {
		return inClass;
	}

	public void setInClass(String inClass) {
		this.inClass = inClass;
	}
    public String getType(){
    	return type;
    }
    
    public void setType(String type){
    	this.type = type;
    }

    @Override
    public abstract Object clone();

    public Node parent()
    {
        return this.parent;
    }

    void parent(@SuppressWarnings("hiding") Node parent)
    {
        this.parent = parent;
    }

    abstract void removeChild(Node child);
    abstract void replaceChild(Node oldChild, Node newChild);

    public void replaceBy(Node node)
    {
        this.parent.replaceChild(this, node);
    }

    protected String toString(Node node)
    {
        if(node != null)
        {
            return node.toString();
        }

        return "";
    }

    protected String toString(List<?> list)
    {
        StringBuffer s = new StringBuffer();

        for(Iterator<?> i = list.iterator(); i.hasNext();)
        {
            s.append(i.next());
        }

        return s.toString();
    }

    @SuppressWarnings("unchecked")
    protected <T extends Node> T cloneNode(T node)
    {
        if(node != null)
        {
            return (T) node.clone();
        }

        return null;
    }

    @SuppressWarnings("unchecked")
    protected <T extends Node> List<T> cloneList(List<T> list)
    {
        List<T> clone = new LinkedList<T>();

        for(T n : list)
        {
            clone.add((T) n.clone());
        }

        return clone;
    }
    
    @Override
    public String getTypeAsString(){
    	return type;
    };
}

