/* This file was generated by SableCC (http://www.sablecc.org/). */

package coolc.compiler.autogen.node;

public abstract class PBranch extends Node
{	
	String inClass;

	public String getInClass() {
		return inClass;
	}

	public void setInClass(String inClass) {
		this.inClass = inClass;
	}
    // Empty body
}
