/* This file was generated by SableCC (http://www.sablecc.org/). */

package coolc.compiler.autogen.node;

public abstract class PExpr extends Node
{
    // Empty body
	String inClass;

	public String getInClass() {
		return inClass;
	}

	public void setInClass(String inClass) {
		this.inClass = inClass;
	}
}
