/* This file was generated by SableCC (http://www.sablecc.org/). */

package coolc.compiler.autogen.node;

import coolc.compiler.visitors.WithPrintableType;

public abstract class PExpr extends Node implements WithPrintableType
{
	private String type;
	
	public String getTypeAsString() {
		return type;
	}
	
	public void setType(String type) {
		this.type = type;
	}
	
}
